### ISSUE TITLE
additional keys to add

### ISSUE THREAD

**Issue by z-vap** [silverBlaze/MouseMoveByKey#1]
Hi.  I have been searching for a program like this for some time.  I have repetitive strain injuries (RSI) in the small muscle fiber tissues of my hands and forearms, due to being overworked (at the office).  Now my hands and arms get tired and sore quicker, and using the mouse for gaming becomes a chore.  So I need to switch off from using the keyboard and the mouse, but with keyboard look being removed from many games these days it limits my enjoyment.    Your app here is the first that i have found which allows for a keyboard look again.   

However I wish there was a way I could add additional keys for left and right.  I typically use both the left/right arrow-combo as well as other keys for left and right (usually A & D).  Just some thoughts for you to consider, by maybe adding a bit of configuration to the app.   If not perhaps a quick howto/tutorial on people editing the code and compiling it on their own.  Thanks

**Comment by silverBlaze** [comment]
This is good feedback. I'll revisit this prototype to add configurable key-mapping, and will also see about packaging up a release so it is easier to download and run without having to compile/build yourself. Thanks!

**Comment by silverBlaze** [comment]
Published a new release at https://github.com/silverBlaze/MouseMoveByKey/releases/tag/v2.0.0

This includes the features for configuring as many keybindings as you want for each mouse-move direction. And the configuration is written to a file when you make changes, so you keep your settings when you close and re-open the program.

I'll leave this issue open until you've had an opportunity to check out the new version. I only have one computer at my disposal today, so I'm unable to do a lot of testing of the new features across multiple platforms. Let me know if you notice any issues.

**Comment by z-vap** [comment]
wow thanks.  let me work on testing this and i'll let you know how it goes

**Comment by z-vap** [comment]
I gotta say, this works far better than I had ever hoped.  Thank you so much for this.  Everything seems to work exactly as expected.  One thing I noticed was, once I got the mouse-move sensitivity to match within the game, that the games Mouselook Sensitivity would then work to slow or speed up the look movement (which makes sense when you think about it).  I say that this can be closed and merged.
